- name: Example for loop
  hosts: all
  become: true
  tasks:
  - name: print fruit names
    debug: 
      msg: "{{ item }}"
    loop:
      - Mango
      - Banana
      - Apple
      - Straberry
    
  - name: install git, wget, vim, httpd
    package: 
      name: "{{ item }}"
      state: present
    loop: 
      - git
      - wget
      - vim
      - httpd
