- name: nginx
  hosts: all
  become: true
 
  tasks:
   - name: install nginx
     apt: 
       name: nginx
       state: present

   - name: service start
     service:
        name: nginx
        state: started  


