- name: install redhat packages
  package:
     - name: {{ items }}     
       state: present
  loop: 
     - {{ app_extra_software }}    
     - httpd 
      
- name: "create document root"
  file: 
     path: /var/www/{{ ap_http_host_dir }}
     state: directory

- name: "copy source" 
  copy:
      src: "{{ap_source_code_location}}"
      dest: "/var/www/{{ ap_http_host_dir }}"    