- name: "Install packages"
  become: true
  package: 
       name: "{{ item }}"
       state: present
  loop:
    - "{{ install_packages }}"

- name: "copy source"
  become: true
  copy:
      src: "source_code"
      dest: /var/www/html/

- name: "start apache2"
  systemd:
       name: apache2
       state: started
       enabled: true      

     